src/main/java/org/ssh2/core/entity/SoftUser.java
package org.ssh2.core.entity;

import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;




/**
 * 用户实体
 * 林景锋
 * 2017年11月23日
 * lv1.0
 */
@Entity
@Table(name = "soft_user")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class SoftUser extends BaseEntity implements UserDetails {

	/**
	 * unique=true是指这个字段的值在这张表里不能重复，所有记录值都要唯一，就像主键那样
	 * nullable=false是这个字段在保存时必需有值，不能还是null值就调用save去保存入库
	 *
	 *private Integer id;
	private String userId;
	private String userName;
	private String userRealName;
	private Integer userSex;
	private Integer userAge;
	private String userPassword;
	private Integer userType;
	private String userAddress;
	private String userTelephone;
	private String userEmail;
	private String userPerId;
	private Integer userPerType;
	private String labId;
	private String sign;
	 */
	private static final long serialVersionUID = -7996992202295686955L;


	@Column(name = "user_create_date")
	private String createDate;// 创建日期

	@Column(name = "user_name", unique = true, nullable = false)
	private String userName;// 用户名

	@Column(name = "user_password")
	private String userPassword;//密码

	@Column(name = "user_telephone")
	private String userTelephone; // 电话

	@Column(name = "user_address")
	private String userAddress;//地址

	@Column(name = "user_email")
	private String userEmail;//邮箱

	@Column(name = "user_realname")
	private String userRealName;//真实姓名

	@Column(name = "user_sex")
	private String userSex;//性别:1-男；2-女





	//inverse表示控制反转，inner join什么的，都是hibernate映射java实体对象类的一些映射约束了什么的
	@ManyToMany(fetch = FetchType.EAGER)//多对多
	@JoinTable(name = "soft_user_role", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "role_id") )
	private Set<SoftRole> user_role;// 所属角色


	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "soft_user_project", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "project_id"))
	private Set<SoftProject> user_project;//所属课程设计

	//	

	@ManyToMany(fetch = FetchType.EAGER)//多对多
	@JoinTable(name = "soft_user_classroom", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "classroom_id") )
	private Set<SoftClassroom> user_classroom;// 所属班级


	public Set<SoftProject> getUser_project() {
		return user_project;
	}

	public void setUser_project(Set<SoftProject> user_project) {
		this.user_project = user_project;
	}


	public Set<SoftClassroom> getUser_classroom() {
		return user_classroom;
	}

	public void setUser_classroom(Set<SoftClassroom> user_classroom) {
		this.user_classroom = user_classroom;
	}

	public SoftUser() {

	}

	public String getCreateDate() {
		return createDate;
	}





	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}





	public String getUserName() {
		return userName;
	}





	public void setUserName(String userName) {
		this.userName = userName;
	}





	public String getUserPassword() {
		return userPassword;
	}





	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}





	public Set<SoftRole> getUser_role() {
		return user_role;
	}





	public void setUser_role(Set<SoftRole> user_role) {
		this.user_role = user_role;
	}





	@Override
	public Collection<? extends GrantedAuthority> getAuthorities() {
		Set<GrantedAuthority> auths = new HashSet<>();
		Set<SoftRole> roles = this.getUser_role();
		// 默认所有的用户有"USER"的权利
		auths.add(new SimpleGrantedAuthority("ROLE_USER"));
		System.out.println("auths="+auths);
		for (SoftRole role : roles) {

			auths.add(new SimpleGrantedAuthority(role.getRoleName()));
			System.out.println("roles==="+auths);
		}
		System.out.println("auths==="+auths);
		return auths;
	}

	public String getUserTelephone() {
		return userTelephone;
	}

	public void setUserTelephone(String userTelephone) {
		this.userTelephone = userTelephone;
	}

	public String getUserAddress() {
		return userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserRealName() {
		return userRealName;
	}

	public void setUserRealName(String userRealName) {
		this.userRealName = userRealName;
	}



	public String getUserSex() {
		return userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}




	@Override
	public String getPassword() {
		return this.userPassword;
	}

	@Override
	public String getUsername() {
		return this.userName;
	}

	@Override
	public boolean isAccountNonExpired() {
		return true;
	}

	@Override
	public boolean isAccountNonLocked() {
		return true;
	}

	@Override
	public boolean isCredentialsNonExpired() {
		return true;
	}

	@Override
	public boolean isEnabled() {
		return true;
	}


	//	@OneToMany(mappedBy="document",cascade = {CascadeType.MERGE, CascadeType.PERSIST,
	//			CascadeType.REFRESH})
	//	private Set<SoftDocument> documents;
	//	@OneToMany(mappedBy="document",cascade = {CascadeType.MERGE, CascadeType.PERSIST,
	//			CascadeType.REFRESH})
	//	private Set<SoftDocument> doucumnet = new HashSet<SoftDocument>();

	//	//inverse表示控制反转，inner join什么的，都是hibernate映射java实体对象类的一些映射约束了什么的
	//	@ManyToMany(fetch = FetchType.EAGER)//多对多
	//	@JoinTable(name = "soft_user_document", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "document_id") )
	//	private Set<SoftDocument> user_document;// 所属文档
}

src/main/java/org/ssh2/web/controller/LogController.java
package org.ssh2.web.controller;



import javax.annotation.Resource;

import org.ssh2.annotation.LogMsg;
import org.ssh2.core.entity.SoftLog;
import org.ssh2.core.service.ILogService;
import org.ssh2.core.util.Page;
import org.ssh2.web.AbstractBaseController;
/**
 * 日志控制器
 * @林景锋
 * 2017年11月27日
 *
 */
public class LogController extends AbstractBaseController {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7586360895369326179L;

	@Resource(name = "logService")
	private ILogService logService;
	
	
	public String listPrompt(){
		Page<SoftLog> page = new Page<SoftLog>();//创建分页对象指定泛型	
		page.setOnePageNum(10);//设置单页记录数
		page.setPageNo(pageNo==null?1:pageNo);//设置当前页数 默认1
		page.setClazz("Log");
		logService.findForPage(page);
		request.put("page", page);
		setPrompt("/WEB-INF/pages/log/log_list.jsp");
		return SUCCESS;
	}
	
	
}

src/main/webapp/WEB-INF/pages/log/log_list.jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<%
	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";
%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<base href="<%=basePath%>" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>系统日志</title>
<link href="css/css/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="css/js/jquery.js"></script>


</head>


<body>

	<div class="place">
    <span>位置：</span>
    <ul class="placeul">
    <li><a href="User_doLogin.action">首页内容</a></li>
    </ul>
    </div>
    
    <div class="rightinfo">
    
    <table class="tablelist">
    	<thead>
    	<tr>
        <th style="width: 50px;">编号</th>
        <th style="width: 90px;">用户名</th> 
        <th style="width: 100px;">IP地址</th>      
        <th style="width: 120px;">操作</th>
        <th style="width: 90px;">方法</th>
        <th>类名</th>
        <th style="width: 140px;">创建日期</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach items="${page.datas}" var="log">
        <tr>
        <td>${log.id}</td>
        <td>${log.username}</td>       
        <td>${log.ipAdd}</td>
        <td>${log.msg}</td>
        <td>${log.method}</td>
        <td>${log.clazz}</td>
        <td>${log.createDate}</td>
        </tr> 
        </c:forEach>     
        </tbody>
    </table>
    
     <div class="pagin">
    	<div class="message">共<i class="blue">${page.total}</i>条记录，当前显示第&nbsp;<i class="blue"><label>${page.pageNo}</label>&nbsp;</i>页</div>
		<ul class="paginList">
			<%@include file="/page/page.html" %>
		</ul>
    </div> 
    
        
    </div>    
    
    <script type="text/javascript">
	$('.tablelist tbody tr:odd').addClass('odd');
	</script>

</body>

</html>